service: beamEducation

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: "20201221"
  timeout: 60
  region: ap-south-1
  stage: prod
  deploymentBucket:
    name: demo-bucket
  environment:
    STAGE: prod
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    REGION: ap-south-1
    BUCKET_NAME: demo-bucket-server
    NODE_ENV: prod

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: demo-bucket

functions:
  node-api:
    handler: index.handler
    events:
      - http:
          path: /welcome
          method: GET
          cors: true
