service: express

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: "20201221"
  timeout: 30  
  region: ap-south-1
  stage: uat
  deploymentBucket:
    name: bucket-lambda-1
  environment:
    STAGE: uat
    REGION: ap-south-1
    BUCKET_NAME: bucket-lambda-1
    NODE_ENV: uat

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource: "arn:aws:s3:::bucket-lambda-1/*"

functions:
  node-api:
    handler: index.handler
    timeout: 30  
    events:
      - http:
          path: /welcome
          method: GET
          cors: true
      - http:
          path: /hello
          method: GET
          cors: true
      - http:
          path: /getProduct
          method: POST
          cors: true
