name: Deploy to AWS Lambda
on:
  push:
    branches:
      - dev
      # - testing
      # - uat
      # - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS Lambda
        run: npx sls deploy --region ap-south-1 --stage dev --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Print deployment success message
        run: echo "Successfully deployed to dev environment $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY"
